pipeline {
   agent any
  tools {nodejs "NodeJs"}
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                git branch: 'main', url: 'https://github.com/thongvm316/eCommerce-MERNStack-FE.git'
                sh 'npm install'
            }
        }
    
        stage('Deploy') {
            steps {
                sh 'npm run build'
            }
        }
    }
}

