pipeline {
    agent {
        docker {
            image 'node:16.14.2'
            args '-p 3000:3000'
        }
    }
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                git 'https://github.com/thongvm316/eCommerce-MERNStack-FE.git'
                dir('eCommerce-MERNStack-FE') {
                    sh 'npm install'
                }
            }
        }
    
        stage('Deliver') {
            steps {
                dir('eCommerce-MERNStack-FE') {
                    sh 'npm run deploy'
                }
            }
        }
    }
}
