pipeline {
   agent any
  tools {nodejs "NodeJs"}
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                git 'https://github.com/thongvm316/eCommerce-MERNStack-FE.git'
                sh 'npmaa install'
            }
        }
    
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deploy-surge.sh'
            }
        }
    }
}

